package com.Eulers.problems;

import java.util.ArrayList;
import java.util.List;

public class ProjectEuler {
    public static void main(String[] args) {

        ProjectEuler pe = new ProjectEuler();

        //Question 1
        //   pe.funtion();

        //Question2
        //   pe.evenFibonacchi();

        //Question3
        pe.largestPrimeFactors(600851475143l);


    }

    /*

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.
*/

    public void function() {
        int sum = 0;
        for (int i = 0; i < 1000; i++) {
            if (i % 3 == 0 || i % 5 == 0) {
                sum = sum + i;
            }
        }
        System.out.println("sum is : " + sum);
    }

    /*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    */

    public void evenFibonacchi() {
        long sum = 0;
        long a = 1, b = 2;
        long c = 0;
        while (true) {
            c = a + b;
            if (c % 2 == 0) {
                sum = sum + c;
            }
            if (c > 4000000) {
                long finalSum = sum + 2;
                System.out.println("Sum is : " + finalSum);
                break;
            }
            a = b;
            b = c;
        }
    }

    /*
     * The prime factors of 13195 are 5, 7, 13 and 29.What is the largest prime factor of the number 600851475143 ?
     *
     * */

    public void largestPrimeFactors(Long number) {
        List<Long> l = new ArrayList<Long>();
        for (int i = 2; checkPrime(i) && i <= number; i++) {
                Long s=number % i;
                if (number % i == 0) {
                    l.add((long)i);
                    largestPrimeFactors(number / i);
                } else {
                    l.add(s);
                }
        }

        for (Long i : l) {
            System.out.println(i);
        }
    }

    private boolean checkPrime(long number) {
        int count = 0;
        for (int i = 1; i <= number; i++) {
            if (number % i == 0) {
                count++;
            }
        }
        return count == 2 ;
    }


}
